# Generated by Django 4.0.3 on 2022-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eloc', models.CharField(max_length=100)),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
