# Generated by Django 4.0.3 on 2022-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogary', models.CharField(max_length=100)),
                ('scategory', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
